export type Categoria =
  | "Carreira e Negócios"
  | "Saúde e Bem Estar"
  | "Criatividade"
  | "Gastronomia"
  | "Estilo de Vida"
  | "Tecnologia";

export interface Expert {
  id: string;
  slug: string;
  nome: string;
  foto: string;
  categoria: Categoria;
  bio: string;
  preco: number;
  duracoes: number[];
  rating: number;
  sessoes: number;
  scarcity?: string;
  doacao?: boolean;
  social: {
    instagram?: string;
    linkedin?: string;
    twitter?: string;
  };
}

export const categorias: Categoria[] = [
  "Carreira e Negócios",
  "Saúde e Bem Estar",
  "Criatividade",
  "Gastronomia",
  "Estilo de Vida",
  "Tecnologia",
];

export const experts: Expert[] = [
  {
    id: "1",
    slug: "andre-carvalhal",
    nome: "André Carvalhal",
    foto: "/mentors/andre-carvalhal/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Consultor de moda e autor. Criador de 'A Moda Imita a Vida'.",
    preco: 350,
    duracoes: [30, 45, 60],
    rating: 4.5,
    sessoes: 563,
    social: {},
  },
  {
    id: "2",
    slug: "andre-do-amaral",
    nome: "André Do Amaral",
    foto: "/mentors/andre-do-amaral/profile.webp",
    categoria: "Criatividade",
    bio: "Designer e diretor criativo. Identidade visual e branding.",
    preco: 250,
    duracoes: [30, 60],
    rating: 4.6,
    sessoes: 547,
    social: {},
  },
  {
    id: "3",
    slug: "estevan-sartoreli",
    nome: "Estevan Sartoreli",
    foto: "/mentors/estevan-sartoreli/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Cofundador e CEO da Dengo Chocolates. Negócios e sustentabilidade.",
    preco: 300,
    duracoes: [30, 60],
    rating: 4.5,
    sessoes: 213,
    doacao: true,
    social: {},
  },
  {
    id: "4",
    slug: "felipe-memoria",
    nome: "Felipe Memória",
    foto: "/mentors/felipe-memoria/profile.webp",
    categoria: "Criatividade",
    bio: "Designer e cofundador da Work & Co. Produto digital.",
    preco: 250,
    duracoes: [15, 30, 60],
    rating: 4.7,
    sessoes: 525,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "5",
    slug: "leandro-assis",
    nome: "Leandro Assis",
    foto: "/mentors/leandro-assis/profile.webp",
    categoria: "Criatividade",
    bio: "Ilustrador e quadrinista. Tirinhas com humor e crítica social.",
    preco: 250,
    duracoes: [15, 30, 45, 60],
    rating: 4.6,
    sessoes: 445,
    social: {},
  },
  {
    id: "6",
    slug: "ludolf-david",
    nome: "Ludolf David",
    foto: "/mentors/ludolf-david/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Criador de conteúdo. Estilo de vida e cultura urbana.",
    preco: 300,
    duracoes: [15, 30, 45, 60],
    rating: 4.9,
    sessoes: 582,
    scarcity: "Apenas 2 vagas essa semana",
    social: {},
  },
  {
    id: "7",
    slug: "manuela-cit",
    nome: "Manuela Cit",
    foto: "/mentors/manuela-cit/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Influenciadora digital e Empreendedora. Cofundadora da Guday e The Simple Gym.",
    preco: 250,
    duracoes: [30, 45, 60],
    rating: 4.9,
    sessoes: 77,
    scarcity: "Apenas 2 vagas essa semana",
    social: {},
  },
  {
    id: "8",
    slug: "mauricio-arruda",
    nome: "Mauricio Arruda",
    foto: "/mentors/mauricio-arruda/profile.webp",
    categoria: "Criatividade",
    bio: "Arquitetura e Design. Sócio e diretor criativo da MAU.",
    preco: 300,
    duracoes: [15, 30, 60],
    rating: 4.7,
    sessoes: 89,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "9",
    slug: "renata-vanzetto",
    nome: "Renata Vanzetto",
    foto: "/mentors/renata-vanzetto/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef e Empreendedora. Mentora do programa Chef de Alto Nível.",
    preco: 350,
    duracoes: [15, 30, 45, 60],
    rating: 5.0,
    sessoes: 169,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "10",
    slug: "camila-coutinho",
    nome: "Camila Coutinho",
    foto: "/mentors/camila-coutinho/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Influenciadora e empreendedora digital. Criadora do Garotas Estúpidas.",
    preco: 350,
    duracoes: [15, 30, 45, 60],
    rating: 4.6,
    sessoes: 230,
    scarcity: "Apenas 2 vagas essa semana",
    social: {},
  },
  {
    id: "11",
    slug: "thassia-naves",
    nome: "Thassia Naves",
    foto: "/mentors/thassia-naves/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Influenciadora de moda e lifestyle. Construção de marca pessoal.",
    preco: 200,
    duracoes: [30, 45, 60],
    rating: 4.7,
    sessoes: 55,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "12",
    slug: "bianca-andrade",
    nome: "Bianca Andrade",
    foto: "/mentors/bianca-andrade/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Empreendedora e influenciadora. Fundadora da Boca Rosa Beauty.",
    preco: 350,
    duracoes: [30, 45, 60],
    rating: 4.7,
    sessoes: 234,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "13",
    slug: "camila-coelho",
    nome: "Camila Coelho",
    foto: "/mentors/camila-coelho/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Influenciadora de moda e beleza. Carreira global e empreendedorismo digital.",
    preco: 350,
    duracoes: [15, 30, 45, 60],
    rating: 4.8,
    sessoes: 398,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "14",
    slug: "helena-bordon",
    nome: "Helena Bordon",
    foto: "/mentors/helena-bordon/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Influenciadora e empreendedora. Cofundadora da 284 Original.",
    preco: 300,
    duracoes: [15, 30, 45, 60],
    rating: 4.8,
    sessoes: 230,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "15",
    slug: "karen-bachini",
    nome: "Karen Bachini",
    foto: "/mentors/karen-bachini/profile.webp",
    categoria: "Estilo de Vida",
    bio: "Criadora de conteúdo e empreendedora. Pioneira do beauty no YouTube brasileiro.",
    preco: 200,
    duracoes: [15, 30, 60],
    rating: 4.6,
    sessoes: 301,
    social: {},
  },
  {
    id: "16",
    slug: "vik-muniz",
    nome: "Vik Muniz",
    foto: "/mentors/vik-muniz/profile.webp",
    categoria: "Criatividade",
    bio: "Artista plástico de reputação internacional. Obras com materiais inusitados.",
    preco: 250,
    duracoes: [30, 60],
    rating: 4.8,
    sessoes: 77,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "17",
    slug: "marcelo-rosenbaum",
    nome: "Marcelo Rosenbaum",
    foto: "/mentors/marcelo-rosenbaum/profile.webp",
    categoria: "Criatividade",
    bio: "Designer e fundador do Instituto A Gente Transforma. Design social.",
    preco: 300,
    duracoes: [30, 45, 60],
    rating: 4.7,
    sessoes: 466,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "18",
    slug: "beatriz-milhazes",
    nome: "Beatriz Milhazes",
    foto: "/mentors/beatriz-milhazes/profile.webp",
    categoria: "Criatividade",
    bio: "Artista plástica reconhecida internacionalmente. Pintura e gravura.",
    preco: 350,
    duracoes: [15, 30, 45, 60],
    rating: 5.0,
    sessoes: 336,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "19",
    slug: "dudu-bertholini",
    nome: "Dudu Bertholini",
    foto: "/mentors/dudu-bertholini/profile.webp",
    categoria: "Criatividade",
    bio: "Estilista, jurado e mentor de moda. Criatividade e identidade.",
    preco: 250,
    duracoes: [30, 60],
    rating: 4.8,
    sessoes: 382,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "20",
    slug: "luiza-trajano",
    nome: "Luiza Trajano",
    foto: "/mentors/luiza-trajano/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Presidente do conselho do Magazine Luiza. Varejo e liderança.",
    preco: 300,
    duracoes: [30, 60],
    rating: 4.8,
    sessoes: 442,
    social: {},
  },
  {
    id: "21",
    slug: "cristina-junqueira",
    nome: "Cristina Junqueira",
    foto: "/mentors/cristina-junqueira/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Cofundadora do Nubank. Fintech e marca de produto.",
    preco: 350,
    duracoes: [15, 30, 45, 60],
    rating: 4.8,
    sessoes: 143,
    social: {},
  },
  {
    id: "22",
    slug: "caito-maia",
    nome: "Caito Maia",
    foto: "/mentors/caito-maia/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Fundador e CEO da Chilli Beans. Varejo e franquias.",
    preco: 350,
    duracoes: [30, 45, 60],
    rating: 4.8,
    sessoes: 328,
    social: {},
  },
  {
    id: "23",
    slug: "flavio-augusto",
    nome: "Flávio Augusto",
    foto: "/mentors/flavio-augusto/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Fundador da Wise Up e do Geração de Valor. Empreendedorismo e vendas.",
    preco: 350,
    duracoes: [15, 30, 60],
    rating: 4.5,
    sessoes: 497,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "24",
    slug: "camila-farani",
    nome: "Camila Farani",
    foto: "/mentors/camila-farani/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Investidora-anjo e fundadora do G2 Capital. Ex-Shark Tank Brasil.",
    preco: 400,
    duracoes: [30, 60],
    rating: 4.5,
    sessoes: 354,
    social: {},
  },
  {
    id: "25",
    slug: "tallis-gomes",
    nome: "Tallis Gomes",
    foto: "/mentors/tallis-gomes/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Fundador do Easy Taxi e da Singu. Construção de startups.",
    preco: 450,
    duracoes: [15, 30, 60],
    rating: 4.6,
    sessoes: 211,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "26",
    slug: "geraldo-rufino",
    nome: "Geraldo Rufino",
    foto: "/mentors/geraldo-rufino/profile.webp",
    categoria: "Carreira e Negócios",
    bio: "Fundador da JR Diesel e palestrante. Empreendedorismo e superação.",
    preco: 450,
    duracoes: [30, 60],
    rating: 4.6,
    sessoes: 352,
    social: {},
  },
  {
    id: "27",
    slug: "pedro-franceschi",
    nome: "Pedro Franceschi",
    foto: "/mentors/pedro-franceschi/profile.webp",
    categoria: "Tecnologia",
    bio: "Cofundador e co-CEO da Brex. Engenharia e produto.",
    preco: 450,
    duracoes: [15, 30, 60],
    rating: 4.7,
    sessoes: 597,
    scarcity: "Apenas 2 vagas essa semana",
    social: {},
  },
  {
    id: "28",
    slug: "henrique-dubugras",
    nome: "Henrique Dubugras",
    foto: "/mentors/henrique-dubugras/profile.webp",
    categoria: "Tecnologia",
    bio: "Cofundador e co-CEO da Brex. Empreendedorismo tech global.",
    preco: 550,
    duracoes: [15, 30, 45, 60],
    rating: 5.0,
    sessoes: 241,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "29",
    slug: "hugo-barra",
    nome: "Hugo Barra",
    foto: "/mentors/hugo-barra/profile.webp",
    categoria: "Tecnologia",
    bio: "Ex-VP do Google Android e ex-Xiaomi. Produto e estratégia tecnológica.",
    preco: 400,
    duracoes: [15, 30, 60],
    rating: 4.8,
    sessoes: 222,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "30",
    slug: "silvio-meira",
    nome: "Silvio Meira",
    foto: "/mentors/silvio-meira/profile.webp",
    categoria: "Tecnologia",
    bio: "Cientista-chefe do Cesar e fundador do Porto Digital. Pesquisa e inovação.",
    preco: 600,
    duracoes: [30, 60],
    rating: 4.7,
    sessoes: 335,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "31",
    slug: "nina-da-hora",
    nome: "Nina da Hora",
    foto: "/mentors/nina-da-hora/profile.webp",
    categoria: "Tecnologia",
    bio: "Cientista da computação e pesquisadora. Ética em IA e inclusão racial.",
    preco: 600,
    duracoes: [15, 30, 45, 60],
    rating: 4.8,
    sessoes: 255,
    social: {},
  },
  {
    id: "32",
    slug: "mike-krieger",
    nome: "Mike Krieger",
    foto: "/mentors/mike-krieger/profile.webp",
    categoria: "Tecnologia",
    bio: "Cofundador do Instagram. Design de produto e empreendedorismo.",
    preco: 400,
    duracoes: [30, 45, 60],
    rating: 4.6,
    sessoes: 442,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "33",
    slug: "fabio-akita",
    nome: "Fábio Akita",
    foto: "/mentors/fabio-akita/profile.webp",
    categoria: "Tecnologia",
    bio: "Engenheiro de software e podcaster. Desenvolvimento e cultura tech.",
    preco: 400,
    duracoes: [15, 30, 60],
    rating: 4.6,
    sessoes: 283,
    social: {},
  },
  {
    id: "34",
    slug: "anderson-thees",
    nome: "Anderson Thees",
    foto: "/mentors/anderson-thees/profile.webp",
    categoria: "Tecnologia",
    bio: "Investidor de venture capital. Ex-Redpoint eventures e construção de startups.",
    preco: 600,
    duracoes: [15, 30, 60],
    rating: 4.8,
    sessoes: 323,
    social: {},
  },
  {
    id: "35",
    slug: "drauzio-varella",
    nome: "Drauzio Varella",
    foto: "/mentors/drauzio-varella/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Médico oncologista e comunicador. Educação em saúde pública.",
    preco: 350,
    duracoes: [30, 60],
    rating: 4.9,
    sessoes: 70,
    social: {},
  },
  {
    id: "36",
    slug: "ana-beatriz-barbosa-silva",
    nome: "Ana Beatriz Barbosa Silva",
    foto: "/mentors/ana-beatriz-barbosa-silva/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Psiquiatra e autora. Saúde mental e relacionamentos.",
    preco: 350,
    duracoes: [15, 30, 60],
    rating: 4.9,
    sessoes: 197,
    social: {},
  },
  {
    id: "37",
    slug: "pedro-calabrez",
    nome: "Pedro Calabrez",
    foto: "/mentors/pedro-calabrez/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Neurocientista e divulgador científico. Comportamento e regulação emocional.",
    preco: 350,
    duracoes: [30, 60],
    rating: 5.0,
    sessoes: 331,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "38",
    slug: "bela-gil",
    nome: "Bela Gil",
    foto: "/mentors/bela-gil/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Apresentadora e culinarista. Alimentação saudável e sustentabilidade.",
    preco: 250,
    duracoes: [30, 60],
    rating: 4.8,
    sessoes: 418,
    social: {},
  },
  {
    id: "39",
    slug: "marcio-atalla",
    nome: "Marcio Atalla",
    foto: "/mentors/marcio-atalla/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Educador físico e treinador. Saúde, longevidade e hábitos.",
    preco: 400,
    duracoes: [30, 45, 60],
    rating: 4.9,
    sessoes: 144,
    scarcity: "Apenas 3 vagas essa semana",
    social: {},
  },
  {
    id: "40",
    slug: "augusto-cury",
    nome: "Augusto Cury",
    foto: "/mentors/augusto-cury/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Psiquiatra e escritor. Inteligência emocional e autoconhecimento.",
    preco: 300,
    duracoes: [15, 30, 45, 60],
    rating: 4.7,
    sessoes: 239,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "41",
    slug: "suzana-herculano-houzel",
    nome: "Suzana Herculano-Houzel",
    foto: "/mentors/suzana-herculano-houzel/profile.webp",
    categoria: "Saúde e Bem Estar",
    bio: "Neurocientista reconhecida internacionalmente. Estudos sobre o cérebro humano.",
    preco: 400,
    duracoes: [30, 60],
    rating: 4.6,
    sessoes: 251,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "42",
    slug: "alex-atala",
    nome: "Alex Atala",
    foto: "/mentors/alex-atala/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do D.O.M. Cozinha brasileira e ingredientes amazônicos.",
    preco: 450,
    duracoes: [15, 30, 45, 60],
    rating: 4.6,
    sessoes: 210,
    social: {},
  },
  {
    id: "43",
    slug: "helena-rizzo",
    nome: "Helena Rizzo",
    foto: "/mentors/helena-rizzo/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do Maní. Eleita Melhor Chef Mulher do Mundo.",
    preco: 300,
    duracoes: [30, 60],
    rating: 4.9,
    sessoes: 290,
    scarcity: "Apenas 1 vaga essa semana",
    social: {},
  },
  {
    id: "44",
    slug: "paola-carosella",
    nome: "Paola Carosella",
    foto: "/mentors/paola-carosella/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef e jurada do MasterChef Brasil. Cozinha autoral.",
    preco: 300,
    duracoes: [15, 30, 45, 60],
    rating: 4.8,
    sessoes: 187,
    social: {},
  },
  {
    id: "45",
    slug: "henrique-fogaca",
    nome: "Henrique Fogaça",
    foto: "/mentors/henrique-fogaca/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do Sal Gastronomia e jurado do MasterChef Brasil.",
    preco: 450,
    duracoes: [30, 60],
    rating: 4.6,
    sessoes: 270,
    social: {},
  },
  {
    id: "46",
    slug: "janaina-rueda",
    nome: "Janaina Rueda",
    foto: "/mentors/janaina-rueda/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do A Casa do Porco. Cozinha brasileira contemporânea.",
    preco: 400,
    duracoes: [30, 45, 60],
    rating: 4.7,
    sessoes: 123,
    social: {},
  },
  {
    id: "47",
    slug: "rodrigo-oliveira",
    nome: "Rodrigo Oliveira",
    foto: "/mentors/rodrigo-oliveira/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do Mocotó. Cozinha nordestina e trabalho social.",
    preco: 300,
    duracoes: [30, 45, 60],
    rating: 4.5,
    sessoes: 274,
    scarcity: "Agenda quase cheia",
    social: {},
  },
  {
    id: "48",
    slug: "manu-buffara",
    nome: "Manu Buffara",
    foto: "/mentors/manu-buffara/profile.webp",
    categoria: "Gastronomia",
    bio: "Chef do Manu (Curitiba). Ingredientes locais e horta urbana.",
    preco: 400,
    duracoes: [30, 60],
    rating: 4.7,
    sessoes: 504,
    social: {},
  },
];
